#include "web_page.h"

const char kIndexHtml[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-Hant\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>輝光管時鐘設定</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box}\n"
    "body{font-family:'PingFang TC','Noto Sans TC','Microsoft JhengHei',sans-serif;margin:0 auto;"
    "padding:16px clamp(28px,8vw,48px) calc(80px + env(safe-area-inset-bottom));"
    "color:#222;max-width:420px}\n"
    "h2{margin:0 0 16px;font-size:1.4rem;text-align:center}\n"
    ".page{display:none;margin-top:0;touch-action:pan-y}\n"
    ".page.active{display:block}\n"
    ".nav{position:fixed;bottom:0;left:clamp(16px,5vw,28px);right:clamp(16px,5vw,28px);"
    "display:flex;background:#fff;border:1px solid #ddd;border-bottom:none;"
    "border-radius:12px 12px 0 0;padding:8px clamp(8px,3vw,16px);"
    "padding-bottom:calc(8px + env(safe-area-inset-bottom));z-index:100;"
    "box-shadow:0 -2px 8px rgba(0,0,0,.06)}\n"
    ".nav-btn{flex:1;padding:12px 8px;min-height:44px;font-size:.95rem;font-weight:600;"
    "border:1px solid #ccc;border-radius:8px;cursor:pointer;background:#fafafa;color:#444;margin:0 4px}\n"
    ".nav-btn.active{background:#222;color:#fff;border-color:#333}\n"
    ".nav-btn:active{background:#eee}\n"
    ".nav-btn.active:active{background:#444}\n"
    "label{display:block;margin:12px 0 6px;font-size:.9rem}\n"
    "input,select{width:100%;padding:10px;margin-bottom:4px;min-height:44px;font-size:1rem}\n"
    "input[type=range]{width:calc(100% - 16px);padding:0;margin:8px auto;display:block;"
    "touch-action:none}\n"
    "input[type=color]{display:block;width:64px;height:48px;padding:4px;"
    "border:1px solid #ccc;border-radius:8px;cursor:pointer}\n"
    "#r{accent-color:#e53935}\n"
    "#g{accent-color:#43a047}\n"
    "#b{accent-color:#1e88e5}\n"
    "#brightness{accent-color:#fb8c00}\n"
    ".volume-row{display:flex;align-items:center;gap:10px;margin:8px 0}\n"
    ".vol-btn{flex:0 0 48px;width:48px;height:48px;min-height:48px;padding:0;"
    "font-size:1.5rem;font-weight:700;line-height:1;border:1px solid #ccc;"
    "border-radius:8px;cursor:pointer;background:#fafafa;color:#222}\n"
    ".vol-btn:active{background:#eee}\n"
    ".vol-btn:disabled{opacity:.4;cursor:default}\n"
    ".volume-meter{flex:1;height:12px;background:#e8e0f0;border-radius:6px;overflow:hidden}\n"
    ".volume-fill{height:100%;width:0;background:#5e35b1;border-radius:6px;"
    "transition:width .15s}\n"
    ".rgb-row{display:flex;align-items:center;gap:8px;padding:0 8px}\n"
    ".rgb-row label{flex:0 0 16px;margin:0}\n"
    ".rgb-row input[type=range]{flex:1}\n"
    ".rgb-row span{flex:0 0 32px;text-align:right;font-size:.85rem;color:#666}\n"
    "button.save-btn{width:100%;padding:18px 24px;font-size:1.25rem;font-weight:700;"
    "margin-top:16px;border-radius:8px;cursor:pointer;border:1px solid #333;background:#222;color:#fff}\n"
    "button.save-btn:active{background:#444}\n"
    "#toast{position:fixed;top:calc(12px + env(safe-area-inset-top));left:50%;"
    "transform:translateX(-50%) translateY(-120%);z-index:200;max-width:min(400px,calc(100% - 32px));"
    "padding:12px 16px;border-radius:10px;font-size:.95rem;font-weight:600;text-align:center;"
    "box-shadow:0 4px 16px rgba(0,0,0,.15);opacity:0;pointer-events:none;"
    "transition:transform .25s ease,opacity .25s ease}\n"
    "#toast.show{transform:translateX(-50%) translateY(0);opacity:1;pointer-events:auto}\n"
    "#toast.ok{background:#e8f5e9;color:#1b5e20;border:1px solid #a5d6a7}\n"
    "#toast.err{background:#ffebee;color:#b71c1c;border:1px solid #ef9a9a}\n"
    ".time-wheels{display:flex;align-items:center;gap:6px;margin-bottom:4px}\n"
    ".time-wheels select{flex:1;text-align:center;text-align-last:center;"
    "font-variant-numeric:tabular-nums}\n"
    ".time-wheels .sep{flex:0 0 auto;font-size:1.2rem;font-weight:700;color:#666}\n"
    "#clockbox{margin:0 0 12px;padding:14px 16px;border-radius:8px;background:#111;"
    "color:#5cff5c;text-align:center}\n"
    "#liveclock{font-family:'Courier New',monospace;font-size:2rem;font-weight:700;"
    "letter-spacing:2px}\n"
    "#clockmeta{font-size:.72rem;color:#8aa88a;margin-top:6px;word-break:break-all}\n"
    "#track_list{list-style:none;margin:0;padding:0}\n"
    "#track_list li{display:flex;align-items:center;justify-content:space-between;"
    "padding:12px 10px;margin-bottom:6px;border:1px solid #ddd;border-radius:8px;"
    "cursor:pointer;background:#fafafa;min-height:44px}\n"
    "#track_list li:active{background:#eee}\n"
    "#track_list li.active{border-color:#5e35b1;background:#f3e8ff}\n"
    "#track_list li.playing{border-color:#43a047;background:#e8f5e9}\n"
    "#track_list li.paused{border-color:#fb8c00;background:#fff3e0}\n"
    ".track-name{font-size:.95rem;font-weight:600}\n"
    ".track-state{font-size:.8rem;color:#666;min-width:4.5em;text-align:right}\n"
    "#track_meta{font-size:.85rem;color:#666;margin:6px 0 10px;min-height:1.2em}\n"
    ".rtc-status{display:flex;align-items:center;gap:10px;margin:8px 0 12px;padding:10px 12px;"
    "border-radius:8px;background:#f9f9f9;border:1px solid #e0e0e0}\n"
    ".rtc-led{flex:0 0 14px;width:14px;height:14px;border-radius:50%;"
    "box-shadow:0 0 6px currentColor}\n"
    ".rtc-led--yellow{background:#fbc02d;color:#fbc02d}\n"
    ".rtc-led--green{background:#43a047;color:#43a047}\n"
    ".rtc-led--red{background:#e53935;color:#e53935}\n"
    "#rtc_status_text{font-size:.88rem;color:#444;line-height:1.3}\n"
    "button.auto-time-btn{margin-top:8px;margin-bottom:4px;background:#1565c0;border-color:#0d47a1}\n"
    "button.auto-time-btn:active{background:#0d47a1}\n"
    ".card{margin:0 0 14px;padding:14px;border:1px solid #ddd;border-radius:12px;background:#fafafa}\n"
    ".card h3{margin:0 0 10px;font-size:1.05rem}\n"
    ".period-hint{font-size:.82rem;color:#666;margin:0 0 12px;line-height:1.35}\n"
    ".switch-row{display:flex;align-items:center;justify-content:space-between;margin:12px 0}\n"
    ".switch-row>span{font-size:.95rem;font-weight:600}\n"
    ".switch{position:relative;display:inline-block;width:52px;height:30px;flex:0 0 52px}\n"
    ".switch input{opacity:0;width:0;height:0;margin:0;padding:0;min-height:0}\n"
    ".switch-slider{position:absolute;cursor:pointer;inset:0;background:#ccc;border-radius:30px;"
    "transition:background .2s}\n"
    ".switch-slider::before{content:'';position:absolute;height:22px;width:22px;left:4px;bottom:4px;"
    "background:#fff;border-radius:50%;transition:transform .2s}\n"
    ".switch input:checked+.switch-slider{background:#222}\n"
    ".switch input:checked+.switch-slider::before{transform:translateX(22px)}\n"
    "#nixie_brightness{accent-color:#fb8c00}\n"
    "#r,#g,#b,#brightness,#nixie_brightness{touch-action:none}\n"
    ".profile-grid{display:grid;grid-template-columns:1fr;gap:8px;margin-top:8px}\n"
    ".profile-row{display:flex;align-items:center;gap:10px}\n"
    ".profile-swatch{width:40px;height:40px;border-radius:8px;border:2px solid #ccc;flex-shrink:0;"
    "cursor:pointer;padding:0;appearance:none;-webkit-appearance:none}\n"
    ".profile-swatch:active{transform:scale(.96)}\n"
    ".profile-swatch.active{border-color:#222;box-shadow:0 0 0 2px #222}\n"
    ".profile-grid .save-btn{margin-top:0;font-size:1rem;padding:14px 12px;flex:1}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div id=\"toast\" role=\"status\" aria-live=\"polite\"></div>\n"
    "<h2>輝光管時鐘設定</h2>\n"
    "<div id=\"ap_info\" class=\"card period-hint\">載入 WiFi 資訊&hellip;</div>\n"
    "<section class=\"page active\" data-page=\"time\">\n"
    "<div class=\"card\">\n"
    "<h3>時鐘狀態</h3>\n"
    "<div id=\"clockbox\">\n"
    "<div id=\"liveclock\">--:--:--</div>\n"
    "<div id=\"clockmeta\">讀取時鐘中&hellip;</div>\n"
    "</div>\n"
    "<div class=\"rtc-status\">"
    "<span id=\"rtc_led\" class=\"rtc-led rtc-led--yellow\"></span>"
    "<span id=\"rtc_status_text\">正在檢查時鐘&hellip;</span></div>\n"
    "<button type=\"button\" class=\"save-btn auto-time-btn\" onclick=\"autoUpdateTime()\">"
    "自動同步時間</button>\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>家用 WiFi（NTP 校時）</h3>\n"
    "<p class=\"period-hint\">設定後時鐘會在每日 06:00 短時間連線同步時間。"
    "密碼僅儲存在時鐘本機。</p>\n"
    "<div id=\"wifi_meta\" class=\"period-hint\">載入中&hellip;</div>\n"
    "<label>WiFi 名稱（SSID）</label>\n"
    "<input type=\"text\" id=\"wifi_ssid\" autocomplete=\"off\" maxlength=\"32\">\n"
    "<label>WiFi 密碼</label>\n"
    "<input type=\"password\" id=\"wifi_pass\" autocomplete=\"off\" maxlength=\"64\">\n"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveWifi()\">儲存 WiFi</button>\n"
    "<button type=\"button\" class=\"save-btn\" style=\"margin-top:8px;background:#555;border-color:#444\" "
    "onclick=\"clearWifi()\">清除 WiFi 設定</button>\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>完成設定</h3>\n"
    "<p class=\"period-hint\">設定完成後請關閉設定 WiFi，手機將自動回到原有網路。</p>\n"
    "<button type=\"button\" class=\"save-btn\" onclick=\"finishSetup()\">完成並關閉設定 WiFi</button>\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>鬧鐘設定</h3>\n"
    "<label>啟用鬧鐘</label>\n"
    "<select id=\"alarm_en\"><option value=\"0\">關閉</option><option value=\"1\">開啟</option></select>\n"
    "<label>鬧鐘時間（24 小時制）</label>\n"
    "<div class=\"time-wheels\">"
    "<select id=\"alarm_h\" aria-label=\"時\"></select>"
    "<span class=\"sep\">:</span>"
    "<select id=\"alarm_m\" aria-label=\"分\"></select>"
    "<span class=\"sep\">:</span>"
    "<select id=\"alarm_s\" aria-label=\"秒\"></select></div>\n"
    "<label>鬧鐘曲目</label>\n"
    "<select id=\"alarm_track\"><option value=\"\">載入曲目中&hellip;</option></select>\n"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveAlarm()\">儲存鬧鐘</button>\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>休眠時段</h3>\n"
    "<p class=\"period-hint\">在設定時段內，輝光管與背光會關閉。"
    "按下任一按鍵可暫時顯示時間 5 秒（輝光管固定亮度 50，背光維持關閉）。</p>\n"
    "<div class=\"switch-row\"><span>休眠模式</span>"
    "<label class=\"switch\"><input type=\"checkbox\" id=\"hib_en\">"
    "<span class=\"switch-slider\"></span></label></div>\n"
    "<label>開始</label><input type=\"time\" id=\"hib_start\" value=\"00:00\" lang=\"en-GB\">\n"
    "<label>結束</label><input type=\"time\" id=\"hib_end\" value=\"07:00\" lang=\"en-GB\">\n"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveSchedule()\">儲存休眠時段</button>\n"
    "</div>\n"
    "</section>\n"
    "<section class=\"page\" data-page=\"backlight\">\n"
    "<div class=\"card\">\n"
    "<h3>背光調整</h3>\n"
    "<p class=\"period-hint\">拖曳滑桿可即時預覽。確認外觀後，到下方設定檔按「儲存」寫入。"
    "點色塊可套用已儲存的設定檔；裝置上亦可用按鈕 2 切換。</p>\n"
    "<label>顏色</label>\n"
    "<input type=\"color\" id=\"color_picker\">\n"
    "<div class=\"rgb-row\"><label>R</label><input type=\"range\" id=\"r\" min=\"0\" max=\"255\">"
    "<span id=\"r_val\"></span></div>\n"
    "<div class=\"rgb-row\"><label>G</label><input type=\"range\" id=\"g\" min=\"0\" max=\"255\">"
    "<span id=\"g_val\"></span></div>\n"
    "<div class=\"rgb-row\"><label>B</label><input type=\"range\" id=\"b\" min=\"0\" max=\"255\">"
    "<span id=\"b_val\"></span></div>\n"
    "<label>亮度 <span id=\"brightness_val\"></span></label>\n"
    "<input type=\"range\" id=\"brightness\" min=\"0\" max=\"255\">\n"
    "<label>動畫</label>\n"
    "<select id=\"backlight_effect\">"
    "<option value=\"0\">靜態</option>"
    "<option value=\"1\">呼吸</option>"
    "<option value=\"2\">彩虹</option>"
    "<option value=\"3\">關閉</option></select>\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>輝光管</h3>\n"
    "<label>輝光管亮度 <span id=\"nixie_brightness_val\"></span></label>\n"
    "<input type=\"range\" id=\"nixie_brightness\" min=\"0\" max=\"255\">\n"
    "<div class=\"switch-row\"><span>數字淡入淡出</span>"
    "<label class=\"switch\"><input type=\"checkbox\" id=\"nixie_transition\">"
    "<span class=\"switch-slider\"></span></label></div>\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>燈光設定檔</h3>\n"
    "<p class=\"period-hint\">點色塊套用該設定檔；按「儲存」把目前外觀寫入該格。</p>\n"
    "<div class=\"profile-grid\">"
    "<div class=\"profile-row\">"
    "<button type=\"button\" class=\"profile-swatch\" id=\"profile_swatch_0\" "
    "aria-label=\"套用設定檔 1\" onclick=\"applyProfile(0)\"></button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(0)\">儲存 1</button></div>"
    "<div class=\"profile-row\">"
    "<button type=\"button\" class=\"profile-swatch\" id=\"profile_swatch_1\" "
    "aria-label=\"套用設定檔 2\" onclick=\"applyProfile(1)\"></button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(1)\">儲存 2</button></div>"
    "<div class=\"profile-row\">"
    "<button type=\"button\" class=\"profile-swatch\" id=\"profile_swatch_2\" "
    "aria-label=\"套用設定檔 3\" onclick=\"applyProfile(2)\"></button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(2)\">儲存 3</button></div>"
    "<div class=\"profile-row\">"
    "<button type=\"button\" class=\"profile-swatch\" id=\"profile_swatch_3\" "
    "aria-label=\"套用設定檔 4\" onclick=\"applyProfile(3)\"></button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(3)\">儲存 4</button></div>"
    "</div>\n"
    "</div>\n"
    "</section>\n"
    "<section class=\"page\" data-page=\"audio\">\n"
    "<div class=\"card\">\n"
    "<h3>音量</h3>\n"
    "<label>音量 <span id=\"volume_val\"></span></label>\n"
    "<div class=\"volume-row\">\n"
    "<button type=\"button\" class=\"vol-btn\" id=\"vol_down\" aria-label=\"降低音量\">&minus;</button>\n"
    "<div class=\"volume-meter\" aria-hidden=\"true\"><div class=\"volume-fill\" id=\"volume_fill\"></div></div>\n"
    "<button type=\"button\" class=\"vol-btn\" id=\"vol_up\" aria-label=\"提高音量\">+</button>\n"
    "</div>\n"
    "<input type=\"hidden\" id=\"volume\" value=\"15\">\n"
    "</div>\n"
    "<div class=\"card\">\n"
    "<h3>曲目</h3>\n"
    "<div id=\"track_meta\">載入曲目中&hellip;</div>\n"
    "<ul id=\"track_list\"></ul>\n"
    "</div>\n"
    "</section>\n"
    "<nav class=\"nav\">\n"
    "<button type=\"button\" class=\"nav-btn active\" data-page=\"time\">時間</button>\n"
    "<button type=\"button\" class=\"nav-btn\" data-page=\"backlight\">燈光</button>\n"
    "<button type=\"button\" class=\"nav-btn\" data-page=\"audio\">音訊</button>\n"
    "</nav>\n"
    "<script>\n"
    "let hibLiveTimer,loading=false,rtcSyncing=false,clockBase=null,audioState={track:0,state:'stopped'},"
    "savedAlarmTrack=1,savedProfiles=[],cachedTracks=[],tracksLoadStarted=false,"
    "previewDirty=false,previewInFlight=false,previewPending=false,previewTimer=null,"
    "previewLastSent=0,previewGeneration=0,PREVIEW_THROTTLE_MS=60,"
    "volInFlight=false,volPending=false,"
    "committedDisplay=null,activePage='time',activeProfileIndex=0,toastTimer=null,"
    "audioToastReady=false,finishCountdownTimer=null;\n"
    "function pad2(n){return String(parseInt(n,10)||0).padStart(2,'0');}\n"
    "function intVal(id,fallback){var v=parseInt(document.getElementById(id).value,10);"
    "return isNaN(v)?fallback:v;}\n"
    "async function apiErrorMessage(r,fallback){try{var j=await r.json();"
    "if(j.error&&j.error.message)return j.error.message;}catch(e){}"
    "return fallback||('請求失敗 ('+r.status+')');}\n"
    "function showToast(msg,ok){var el=document.getElementById('toast');"
    "el.textContent=msg;el.className=(ok===false?'err':'ok')+' show';"
    "clearTimeout(toastTimer);"
    "toastTimer=setTimeout(function(){el.classList.remove('show');},3000);}\n"
    "async function loadApStatus(){try{var r=await fetch('/api/ap/status'),j=await r.json();"
    "var el=document.getElementById('ap_info');"
    "if(!j.active){el.textContent='設定 WiFi 未開啟';return;}"
    "el.innerHTML='請連線：<b>'+j.ssid+'</b>　密碼：<b>'+j.password+'</b><br>'"
    "+'Nixie 顯示：<b>'+String(j.session_code).padStart(4,'0')+'</b>　"
    "剩餘 '+j.remaining_sec+' 秒';}catch(e){"
    "document.getElementById('ap_info').textContent='無法讀取 AP 狀態';}}\n"
    "async function loadWifi(){try{var r=await fetch('/api/wifi'),j=await r.json();"
    "var meta=document.getElementById('wifi_meta');"
    "if(j.configured){meta.textContent='目前已設定：'+j.ssid;"
    "document.getElementById('wifi_ssid').value=j.ssid||'';}else{"
    "meta.textContent='尚未設定家用 WiFi';}}catch(e){"
    "document.getElementById('wifi_meta').textContent='無法讀取 WiFi 設定';}}\n"
    "async function saveWifi(){var ssid=document.getElementById('wifi_ssid').value.trim();"
    "if(!ssid){showToast('請輸入 WiFi 名稱',false);return;}"
    "var body={ssid:ssid,password:document.getElementById('wifi_pass').value};"
    "try{var r=await fetch('/api/wifi',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(!r.ok){showToast(await apiErrorMessage(r,'儲存 WiFi 失敗'),false);return;}"
    "showToast('WiFi 已儲存',true);loadWifi();}catch(e){showToast('儲存 WiFi 失敗',false);}}\n"
    "async function clearWifi(){try{var r=await fetch('/api/wifi',{method:'DELETE'});"
    "if(!r.ok){showToast(await apiErrorMessage(r,'清除失敗'),false);return;}"
    "document.getElementById('wifi_ssid').value='';document.getElementById('wifi_pass').value='';"
    "showToast('WiFi 設定已清除',true);loadWifi();}catch(e){showToast('清除失敗',false);}}\n"
    "function finishSetup(){var sec=3;clearInterval(finishCountdownTimer);"
    "showToast(''+sec+' 秒後關閉設定 WiFi…',true);"
    "finishCountdownTimer=setInterval(async function(){sec--;"
    "if(sec>0){showToast(''+sec+' 秒後關閉設定 WiFi…',true);return;}"
    "clearInterval(finishCountdownTimer);"
    "try{await fetch('/api/ap/stop',{method:'POST'});"
    "showToast('設定 WiFi 已關閉，請回到原有 WiFi 或行動網路',true);"
    "}catch(e){showToast('關閉設定 WiFi 失敗',false);}},1000);}\n"
    "function fillSelectRange(sel,maxExclusive){sel.innerHTML='';"
    "for(var i=0;i<maxExclusive;i++){var opt=document.createElement('option');"
    "opt.value=pad2(i);opt.textContent=pad2(i);sel.appendChild(opt);}}\n"
    "function initAlarmTimeWheels(){fillSelectRange(document.getElementById('alarm_h'),24);"
    "fillSelectRange(document.getElementById('alarm_m'),60);"
    "fillSelectRange(document.getElementById('alarm_s'),60);}\n"
    "function getAlarmTime(){return pad2(document.getElementById('alarm_h').value)+':'"
    "+pad2(document.getElementById('alarm_m').value)+':'"
    "+pad2(document.getElementById('alarm_s').value);}\n"
    "function setAlarmTime(v){var p=(v||'00:00:00').split(':');"
    "document.getElementById('alarm_h').value=pad2(p[0]||0);"
    "document.getElementById('alarm_m').value=pad2(p[1]||0);"
    "document.getElementById('alarm_s').value=pad2(p[2]||0);}\n"
    "function timeClock(j){return(j&&j.clock)||{};}\n"
    "function rtcCalibrated(j){return!!timeClock(j).rtc_calibrated;}\n"
    "function tzFromTime(j){var c=timeClock(j);"
    "return typeof c.timezone_offset_hours==='number'?c.timezone_offset_hours:0;}\n"
    "function updateRtcIndicator(j,errMsg){var led=document.getElementById('rtc_led'),"
    "txt=document.getElementById('rtc_status_text');led.className='rtc-led';"
    "if(errMsg){led.classList.add('rtc-led--red');txt.textContent=errMsg;return;}"
    "if(!j){led.classList.add('rtc-led--yellow');txt.textContent='正在檢查時鐘\\u2026';return;}"
    "if(rtcCalibrated(j)&&j.time_valid&&!j.osf){led.classList.add('rtc-led--green');"
    "txt.textContent='時鐘已同步';return;}"
    "if(!j.time_valid){led.classList.add('rtc-led--red');"
    "txt.textContent='時鐘錯誤：時間無效';return;}"
    "if(j.osf){led.classList.add('rtc-led--yellow');"
    "txt.textContent='備用電池電力不足，請重新同步時間';return;}"
    "led.classList.add('rtc-led--yellow');"
    "txt.textContent='時鐘尚未同步 \\u2013 請點「自動同步時間」';}\n"
    "function phoneLocalNow(){var now=new Date(),tz=-now.getTimezoneOffset()/60,"
    "date=now.getFullYear()+'-'+pad2(now.getMonth()+1)+'-'+pad2(now.getDate()),"
    "time=pad2(now.getHours())+':'+pad2(now.getMinutes())+':'+pad2(now.getSeconds());"
    "return{tz:tz,date:date,time:time,timeStr:date+' '+time};}\n"
    "function timeSyncStatusMsg(j){if(rtcCalibrated(j)&&j.time_valid&&!j.osf)"
    "return{ok:true,msg:'時間同步成功'};"
    "if(j.osf)return{ok:false,msg:'警告：備用電池電力不足，請重新同步時間'};"
    "if(!j.time_valid)return{ok:false,msg:'時鐘錯誤：寫入失敗或時鐘無法使用'};"
    "return{ok:false,msg:'時鐘錯誤：同步後未完成校準'};}\n"
    "async function verifyTimeSync(){await new Promise(function(res){setTimeout(res,700);});"
    "var tr=await fetch('/api/time');if(!tr.ok)throw new Error('同步後無法讀取時間');"
    "return tr.json();}\n"
    "function fmtLocal(utcEpoch,tz){var e=utcEpoch+tz*3600;"
    "var d=new Date(e*1000);"
    "return d.getUTCFullYear()+'-'+pad2(d.getUTCMonth()+1)+'-'+pad2(d.getUTCDate())+' '+"
    "pad2(d.getUTCHours())+':'+pad2(d.getUTCMinutes())+':'+pad2(d.getUTCSeconds());}\n"
    "function fmtTz(tz){return 'UTC'+(tz>=0?'+':'')+tz;}\n"
    "async function syncClock(){try{var r=await fetch('/api/time'),j=await r.json();"
    "if(!rtcSyncing)updateRtcIndicator(j,null);"
    "if(j.time_valid&&typeof j.unix_utc==='number'){"
    "clockBase={utc:j.unix_utc,perf:Date.now(),tz:tzFromTime(j),osf:j.osf};"
    "tickClock();}"
    "else{clockBase=null;"
    "document.getElementById('liveclock').textContent='尚未設定時間';"
    "document.getElementById('clockmeta').textContent="
    "'時間無效 \\u2013 請點「自動同步時間」';}"
    "}catch(e){if(!rtcSyncing)updateRtcIndicator(null,'時鐘錯誤：無法連線到裝置');}}\n"
    "function tickClock(){if(!clockBase)return;"
    "var nowUtc=clockBase.utc+Math.floor((Date.now()-clockBase.perf)/1000);"
    "document.getElementById('liveclock').textContent=fmtLocal(nowUtc,clockBase.tz);"
    "var meta='本地時間 ('+fmtTz(clockBase.tz)+')';"
    "if(clockBase.osf)meta+=' | 備用電池異常';"
    "document.getElementById('clockmeta').textContent=meta;}\n"
    "setInterval(tickClock,1000);setInterval(syncClock,10000);syncClock();\n"
    "function normalizeAlarm(v){if(!v)return'00:00:00';const p=v.split(':');"
    "return pad2(p[0]||0)+':'+pad2(p[1]||0)+':'+pad2(p[2]||0);}\n"
    "function rgbToHex(r,g,b){return'#'+[r,g,b].map(function(x){"
    "var h=parseInt(x).toString(16);return h.length===1?'0'+h:h;}).join('');}\n"
    "function hexToRgb(hex){var m=/^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(hex);"
    "return m?{r:parseInt(m[1],16),g:parseInt(m[2],16),b:parseInt(m[3],16)}"
    ":{r:0,g:0,b:0};}\n"
    "function setRgb(r,g,b){document.getElementById('r').value=r;"
    "document.getElementById('g').value=g;document.getElementById('b').value=b;"
    "document.getElementById('r_val').textContent=r;"
    "document.getElementById('g_val').textContent=g;"
    "document.getElementById('b_val').textContent=b;"
    "document.getElementById('color_picker').value=rgbToHex(r,g,b);}\n"
    "function effectToApi(v){return['static','breath','rainbow','off'][parseInt(v,10)]||'static';}\n"
    "function effectFromApi(v){var i=['static','breath','rainbow','off'].indexOf(v);return i<0?0:i;}\n"
    "function collectDisplay(){return{backlight:{color:{r:intVal('r',0),g:intVal('g',0),"
    "b:intVal('b',0)},brightness:intVal('brightness',128),"
    "effect:effectToApi(document.getElementById('backlight_effect').value)},"
    "nixie:{brightness:intVal('nixie_brightness',255),transition:"
    "document.getElementById('nixie_transition').checked?'fade':'instant'}};}\n"
    "function snapshotDisplay(d){return JSON.parse(JSON.stringify(d));}\n"
    "function applyDisplayFromSnapshot(d){if(!d)return;"
    "var bl=d.backlight||{},c=bl.color||{},nx=d.nixie||{};"
    "setRgb(c.r||0,c.g||0,c.b||0);"
    "document.getElementById('brightness').value=bl.brightness??128;"
    "document.getElementById('brightness_val').textContent=bl.brightness??128;"
    "document.getElementById('backlight_effect').value=effectFromApi(bl.effect);"
    "document.getElementById('nixie_brightness').value=nx.brightness??255;"
    "document.getElementById('nixie_brightness_val').textContent=nx.brightness??255;"
    "document.getElementById('nixie_transition').checked=nx.transition==='fade';}\n"
    "function profileSwatchColor(p){var bl=(p&&p.backlight)||{},c=bl.color||{};"
    "return'rgb('+(c.r||0)+','+(c.g||0)+','+(c.b||0)+')';}\n"
    "function updateProfileSwatches(){for(var i=0;i<4;i++){"
    "var el=document.getElementById('profile_swatch_'+i);"
    "if(el){el.style.background=profileSwatchColor(savedProfiles[i]);"
    "el.classList.toggle('active',i===activeProfileIndex);}}}\n"
    "function onDisplayControlChanged(){if(loading)return;previewDirty=true;scheduleDisplayPreview();}\n"
    "function scheduleDisplayPreview(){if(loading||!previewDirty)return;"
    "var now=Date.now(),elapsed=now-previewLastSent;"
    "if(!previewInFlight&&elapsed>=PREVIEW_THROTTLE_MS){"
    "clearTimeout(previewTimer);previewTimer=null;applyDisplayPreview();return;}"
    "previewPending=true;if(previewTimer)return;"
    "var wait=previewInFlight?PREVIEW_THROTTLE_MS:Math.max(0,PREVIEW_THROTTLE_MS-elapsed);"
    "previewTimer=setTimeout(function(){previewTimer=null;"
    "if(previewDirty)applyDisplayPreview();},wait);}\n"
    "function flushDisplayPreview(){if(loading)return;"
    "clearTimeout(previewTimer);previewTimer=null;"
    "if(previewDirty)applyDisplayPreview();}\n"
    "async function applyDisplayPreview(){if(loading||!previewDirty)return;"
    "if(previewInFlight){previewPending=true;return;}"
    "clearTimeout(previewTimer);previewTimer=null;"
    "var gen=previewGeneration;"
    "previewInFlight=true;previewPending=false;previewLastSent=Date.now();"
    "try{await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({display:collectDisplay(),persist:false})});}"
    "catch(e){}finally{previewInFlight=false;"
    "if(gen!==previewGeneration||!previewDirty){previewPending=false;return;}"
    "if(previewPending)applyDisplayPreview();}}\n"
    "function invalidateDisplayPreview(){previewDirty=false;previewPending=false;"
    "previewGeneration++;clearTimeout(previewTimer);previewTimer=null;}\n"
    "async function cancelDisplayPreview(){if(!previewDirty)return;"
    "invalidateDisplayPreview();"
    "try{await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({preview:{cancel:true}})});}catch(e){}"
    "if(committedDisplay)applyDisplayFromSnapshot(committedDisplay);}\n"
    "function cancelDisplayPreviewBeacon(){if(!previewDirty)return;"
    "invalidateDisplayPreview();"
    "try{fetch('/api/settings',{method:'POST',keepalive:true,"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({preview:{cancel:true}})});}catch(e){}}\n"
    "function bindLiveSlider(el,onValue,onFlush){var dragging=false;"
    "function notify(){onValue(el.value);}"
    "function endDrag(){if(!dragging)return;dragging=false;notify();if(onFlush)onFlush();}"
    "el.addEventListener('pointerdown',function(e){if(loading)return;"
    "dragging=true;if(el.setPointerCapture)el.setPointerCapture(e.pointerId);notify();});"
    "el.addEventListener('pointermove',function(){if(dragging)notify();});"
    "el.addEventListener('pointerup',endDrag);"
    "el.addEventListener('pointercancel',function(){dragging=false;});"
    "el.addEventListener('input',notify);}\n"
    "function syncColorPickerFromRgb(){document.getElementById('color_picker').value=rgbToHex("
    "document.getElementById('r').value,document.getElementById('g').value,"
    "document.getElementById('b').value);}\n"
    "function bindDisplayControls(){"
    "bindLiveSlider(document.getElementById('r'),function(v){"
    "document.getElementById('r_val').textContent=v;syncColorPickerFromRgb();onDisplayControlChanged();},"
    "flushDisplayPreview);"
    "bindLiveSlider(document.getElementById('g'),function(v){"
    "document.getElementById('g_val').textContent=v;syncColorPickerFromRgb();onDisplayControlChanged();},"
    "flushDisplayPreview);"
    "bindLiveSlider(document.getElementById('b'),function(v){"
    "document.getElementById('b_val').textContent=v;syncColorPickerFromRgb();onDisplayControlChanged();},"
    "flushDisplayPreview);"
    "bindLiveSlider(document.getElementById('brightness'),function(v){"
    "document.getElementById('brightness_val').textContent=v;onDisplayControlChanged();},"
    "flushDisplayPreview);"
    "bindLiveSlider(document.getElementById('nixie_brightness'),function(v){"
    "document.getElementById('nixie_brightness_val').textContent=v;onDisplayControlChanged();},"
    "flushDisplayPreview);"
    "document.getElementById('color_picker').addEventListener('change',function(){"
    "var c=hexToRgb(this.value);setRgb(c.r,c.g,c.b);onDisplayControlChanged();});"
    "document.getElementById('backlight_effect').addEventListener('change',onDisplayControlChanged);"
    "document.getElementById('nixie_transition').addEventListener('change',onDisplayControlChanged);}\n"
    "function getVolume(){var v=intVal('volume',15);return v<0?0:(v>30?30:v);}\n"
    "function setVolumeUi(v){v=v|0;if(v<0)v=0;if(v>30)v=30;"
    "document.getElementById('volume').value=v;"
    "document.getElementById('volume_val').textContent=v;"
    "document.getElementById('volume_fill').style.width=(v/30*100)+'%';"
    "document.getElementById('vol_down').disabled=v<=0;"
    "document.getElementById('vol_up').disabled=v>=30;}\n"
    "function nudgeVolume(delta){if(loading)return;"
    "var next=getVolume()+delta;if(next<0||next>30)return;"
    "setVolumeUi(next);applyVolume();}\n"
    "async function applyVolume(){if(loading)return;"
    "if(volInFlight){volPending=true;return;}"
    "volInFlight=true;volPending=false;"
    "var body={audio:{volume:getVolume()}};"
    "try{await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch(e){}"
    "finally{volInFlight=false;if(volPending)applyVolume();}}\n"
    "async function applyProfile(index){if(loading)return;"
    "try{var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({profiles:{active_index:index},persist:true})});"
    "if(!r.ok){showToast(await apiErrorMessage(r,'套用設定檔失敗'),false);return;}"
    "activeProfileIndex=index;"
    "if(savedProfiles[index]){committedDisplay=snapshotDisplay(savedProfiles[index]);"
    "applyDisplayFromSnapshot(committedDisplay);}"
    "invalidateDisplayPreview();updateProfileSwatches();"
    "showToast('已套用設定檔 '+(index+1),true);"
    "}catch(e){showToast('套用設定檔失敗',false);}}\n"
    "async function saveProfile(index){var body={display:collectDisplay(),"
    "profiles:{save_index:index},persist:true};"
    "try{var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(r.ok){savedProfiles[index]=body.display;committedDisplay=snapshotDisplay(body.display);"
    "activeProfileIndex=index;invalidateDisplayPreview();updateProfileSwatches();"
    "showToast('設定檔 '+(index+1)+' 已儲存',true);}"
    "else showToast('儲存設定檔失敗',false);"
    "}catch(e){showToast('儲存設定檔失敗',false);}}\n"
    "async function autoUpdateTime(){if(rtcSyncing)return;rtcSyncing=true;"
    "document.getElementById('rtc_led').className='rtc-led rtc-led--yellow';"
    "document.getElementById('rtc_status_text').textContent="
    "'正在從此裝置同步時間\\u2026';"
    "try{var loc=phoneLocalNow();"
    "var body={clock:{timezone_offset_hours:loc.tz,local_time:loc.timeStr},"
    "alarm:{enabled:document.getElementById('alarm_en').value==1,"
    "time:normalizeAlarm(getAlarmTime())}};"
    "var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(!r.ok){updateRtcIndicator(null,'時鐘錯誤：伺服器拒絕時間設定 ('+r.status+')');"
    "showToast('時鐘錯誤：儲存失敗 ('+r.status+')',false);"
    "rtcSyncing=false;return;}"
    "var tj=await verifyTimeSync(),st=timeSyncStatusMsg(tj);"
    "updateRtcIndicator(tj,null);"
    "showToast(st.msg,st.ok);"
    "if(st.ok)syncClock();"
    "}catch(e){updateRtcIndicator(null,'時鐘錯誤：'+e.message);"
    "showToast('時鐘錯誤：'+e.message,false);}"
    "rtcSyncing=false;}\n"
    "function normalizeHm(v){if(!v)return'00:00';const p=v.split(':');"
    "return pad2(p[0]||0)+':'+pad2(p[1]||0);}\n"
    "function loadHibernation(h){if(!h)return;"
    "document.getElementById('hib_en').checked=!!h.enabled;"
    "document.getElementById('hib_start').value=normalizeHm(h.start||'00:00');"
    "document.getElementById('hib_end').value=normalizeHm(h.end||'07:00');}\n"
    "function collectHibernation(){return{"
    "enabled:document.getElementById('hib_en').checked,"
    "start:normalizeHm(document.getElementById('hib_start').value),"
    "end:normalizeHm(document.getElementById('hib_end').value)"
    "};}\n"
    "async function saveSchedule(){var ok=await applyHibLive();"
    "showToast(ok?'休眠時段已儲存':'儲存休眠時段失敗',ok);}\n"
    "function scheduleHibLive(){if(loading)return;clearTimeout(hibLiveTimer);"
    "hibLiveTimer=setTimeout(applyHibLive,200);}\n"
    "async function applyHibLive(){var body={hibernation:collectHibernation()};"
    "try{var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "return r.ok;}catch(e){return false;}}\n"
    "async function saveAlarm(){var at=document.getElementById('alarm_track').value;"
    "var body={alarm:{enabled:document.getElementById('alarm_en').value==1,"
    "time:normalizeAlarm(getAlarmTime())}};"
    "if(at)body.alarm.track=parseInt(at,10);"
    "var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(!r.ok){showToast(await apiErrorMessage(r,'儲存鬧鐘失敗'),false);return;}"
    "showToast('鬧鐘已儲存',true);"
    "syncClock();}\n"
    "document.getElementById('vol_down').addEventListener('click',function(){nudgeVolume(-1);});\n"
    "document.getElementById('vol_up').addEventListener('click',function(){nudgeVolume(1);});\n"
    "document.getElementById('hib_en').addEventListener('change',scheduleHibLive);\n"
    "document.getElementById('hib_start').addEventListener('change',scheduleHibLive);\n"
    "document.getElementById('hib_end').addEventListener('change',scheduleHibLive);\n"
    "function trackStateLabel(s){return s==='playing'?'\\u25b6 播放中':"
    "s==='paused'?'\\u23f8 已暫停':'\\u25cb 已停止';}\n"
    "function applyAudioState(track,state){var prevT=audioState.track,prevS=audioState.state;"
    "audioState.track=track||0;audioState.state=state||'stopped';updateTrackUi();"
    "if(!audioToastReady)return;"
    "if(track===prevT&&state===prevS)return;"
    "if(state==='playing'||state==='paused'||"
    "(state==='stopped'&&(prevS==='playing'||prevS==='paused'))){"
    "var name=String(audioState.track).padStart(4,'0')+'.mp3';"
    "showToast(trackStateLabel(audioState.state)+(audioState.track>0?' \\u2013 '+name:''),true);}}\n"
    "function populateAlarmTrackSelect(tracks){var sel=document.getElementById('alarm_track');"
    "sel.innerHTML='';tracks.forEach(function(t){var opt=document.createElement('option');"
    "opt.value=t.id;opt.textContent=t.name;sel.appendChild(opt);});"
    "if(savedAlarmTrack)sel.value=String(savedAlarmTrack);}\n"
    "function renderTracks(tracks){var ul=document.getElementById('track_list');ul.innerHTML='';"
    "tracks.forEach(function(t){var li=document.createElement('li');"
    "li.dataset.track=t.id;li.innerHTML='<span class=\"track-name\">'+t.name+'</span>'"
    "+'<span class=\"track-state\"></span>';li.onclick=function(){toggleTrack(t.id);};"
    "ul.appendChild(li);});updateTrackUi();}\n"
    "function updateTrackUi(){document.querySelectorAll('#track_list li').forEach(function(li){"
    "var id=parseInt(li.dataset.track,10),st=li.querySelector('.track-state');"
    "li.classList.remove('active','playing','paused');"
    "if(id===audioState.track&&audioState.track>0){li.classList.add('active');"
    "if(audioState.state==='playing')li.classList.add('playing');"
    "if(audioState.state==='paused')li.classList.add('paused');"
    "st.textContent=trackStateLabel(audioState.state);}else{st.textContent='';}});"
    "var meta=document.getElementById('track_meta');"
    "if(audioState.track>0&&audioState.state!=='stopped'){"
    "meta.textContent='目前：'+String(audioState.track).padStart(4,'0')+'.mp3 \\u2013 '"
    "+trackStateLabel(audioState.state);}else if(meta.dataset.loaded==='1'){"
    "meta.textContent='點選曲目播放（SD:/mp3/）';}}\n"
    "async function syncAudioStatus(){try{var r=await fetch('/api/audio/status'),j=await r.json();"
    "applyAudioState(j.track||0,j.state||'stopped');"
    "if(!audioToastReady)audioToastReady=true;"
    "}catch(e){}}\n"
    "function trackErrorMsg(j){if(j.error==='query_failed')"
    "return'無法查詢 SD 卡上的 mp3/ 資料夾。';"
    "return'無法讀取 SD 卡';}\n"
    "async function loadTracks(){if(tracksLoadStarted)return;tracksLoadStarted=true;"
    "var meta=document.getElementById('track_meta');"
    "meta.textContent='載入曲目中\\u2026';try{"
    "var r=await fetch('/api/audio/tracks'),j=await r.json();"
    "if(j.error||!j.tracks||j.tracks.length===0){"
    "meta.textContent=j.error?trackErrorMsg(j):'mp3/ 資料夾沒有曲目';"
    "document.getElementById('track_list').innerHTML='';"
    "document.getElementById('alarm_track').innerHTML="
    "'<option value=\"\">沒有可用曲目</option>';meta.dataset.loaded='0';return;}"
    "meta.dataset.loaded='1';meta.textContent='mp3/ 共 '+j.count+' 首曲目';"
    "cachedTracks=j.tracks;populateAlarmTrackSelect(j.tracks);renderTracks(j.tracks);await syncAudioStatus();"
    "}catch(e){meta.textContent='載入曲目失敗';}}\n"
    "async function toggleTrack(id){try{"
    "var r=await fetch('/api/audio/play',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify({track:id})});"
    "if(!r.ok)return;var j=await r.json();"
    "audioToastReady=true;"
    "applyAudioState(j.track||0,j.state||'stopped');"
    "}catch(e){}}\n"
    "setInterval(syncAudioStatus,2000);\n"
    "async function load(){loading=true;try{"
    "var sr=await fetch('/api/settings'),sj=await sr.json();"
    "var al=sj.alarm||{},d=sj.display||{},bl=d.backlight||{},"
    "c=bl.color||{},nx=d.nixie||{},au=sj.audio||{},pr=sj.profiles||{};"
    "document.getElementById('alarm_en').value=al.enabled?1:0;"
    "setAlarmTime(al.time);"
    "savedAlarmTrack=al.track||1;"
    "if(cachedTracks.length>0){populateAlarmTrackSelect(cachedTracks);}"
    "savedProfiles=(pr.items||[]).map(function(p){return p.display;});"
    "activeProfileIndex=typeof pr.active_index==='number'?pr.active_index:0;"
    "applyDisplayFromSnapshot(d);committedDisplay=snapshotDisplay(d);updateProfileSwatches();"
    "setVolumeUi(au.volume??15);"
    "loadHibernation(sj.hibernation);"
    "try{var tr=await fetch('/api/time'),tj=await tr.json();"
    "updateRtcIndicator(tj,null);"
    "if(!rtcCalibrated(tj)&&!rtcSyncing){await autoUpdateTime();}"
    "}catch(e){updateRtcIndicator(null,'時鐘錯誤：無法連線到裝置');}"
    "}catch(e){}finally{loading=false;}}\n"
    "async function showPage(name){"
    "if(activePage==='backlight'&&name!=='backlight')await cancelDisplayPreview();"
    "document.querySelectorAll('.page').forEach(function(el){"
    "el.classList.toggle('active',el.dataset.page===name);});"
    "document.querySelectorAll('.nav-btn').forEach(function(btn){"
    "btn.classList.toggle('active',btn.dataset.page===name);});"
    "activePage=name;location.hash=name;"
    "if(name==='backlight'&&committedDisplay)applyDisplayFromSnapshot(committedDisplay);}\n"
    "document.querySelectorAll('.nav-btn').forEach(function(btn){"
    "btn.addEventListener('click',function(){showPage(btn.dataset.page);});});\n"
    "window.addEventListener('hashchange',function(){"
    "var p=(location.hash||'#time').slice(1);"
    "if(['time','backlight','audio'].indexOf(p)>=0)showPage(p);});\n"
    "window.addEventListener('pagehide',cancelDisplayPreviewBeacon);\n"
    "initAlarmTimeWheels();\n"
    "bindDisplayControls();\n"
    "loadTracks();\n"
    "loadApStatus();loadWifi();setInterval(loadApStatus,5000);\n"
    "var initial=(location.hash||'#time').slice(1);"
    "if(['time','backlight','audio'].indexOf(initial)<0)initial='time';"
    "load().then(function(){return showPage(initial);});\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
