#include "web_page.h"

const char kIndexHtml[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>Nixie Clock Setup</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box}\n"
    "body{font-family:Arial,sans-serif;margin:0 auto;"
    "padding:16px clamp(28px,8vw,48px) calc(80px + env(safe-area-inset-bottom));"
    "color:#222;max-width:420px}\n"
    "h2{margin:0 0 16px;font-size:1.4rem}\n"
    ".page{display:none;margin-top:0;touch-action:pan-y}\n"
    ".page.active{display:block}\n"
    ".nav{position:fixed;bottom:0;left:clamp(16px,5vw,28px);right:clamp(16px,5vw,28px);"
    "display:flex;background:#fff;border:1px solid #ddd;border-bottom:none;"
    "border-radius:12px 12px 0 0;padding:8px clamp(8px,3vw,16px);"
    "padding-bottom:calc(8px + env(safe-area-inset-bottom));z-index:100;"
    "box-shadow:0 -2px 8px rgba(0,0,0,.06)}\n"
    ".nav-btn{flex:1;padding:12px 8px;min-height:44px;font-size:.95rem;font-weight:600;"
    "border:1px solid #ccc;border-radius:8px;cursor:pointer;background:#fafafa;color:#444;margin:0 4px}\n"
    ".nav-btn.active{background:#222;color:#fff;border-color:#333}\n"
    ".nav-btn:active{background:#eee}\n"
    ".nav-btn.active:active{background:#444}\n"
    "label{display:block;margin:12px 0 6px;font-size:.9rem}\n"
    "input,select{width:100%;padding:10px;margin-bottom:4px;min-height:44px;font-size:1rem}\n"
    "input[type=range]{width:calc(100% - 16px);padding:0;margin:8px auto;display:block;"
    "touch-action:none}\n"
    "input[type=color]{display:block;width:64px;height:48px;padding:4px;"
    "border:1px solid #ccc;border-radius:8px;cursor:pointer}\n"
    "#r{accent-color:#e53935}\n"
    "#g{accent-color:#43a047}\n"
    "#b{accent-color:#1e88e5}\n"
    "#brightness{accent-color:#fb8c00}\n"
    "#volume{accent-color:#5e35b1}\n"
    ".rgb-row{display:flex;align-items:center;gap:8px;padding:0 8px}\n"
    ".rgb-row label{flex:0 0 16px;margin:0}\n"
    ".rgb-row input[type=range]{flex:1}\n"
    ".rgb-row span{flex:0 0 32px;text-align:right;font-size:.85rem;color:#666}\n"
    "button.save-btn{width:100%;padding:18px 24px;font-size:1.25rem;font-weight:700;"
    "margin-top:16px;border-radius:8px;cursor:pointer;border:1px solid #333;background:#222;color:#fff}\n"
    "button.save-btn:active{background:#444}\n"
    "#status{margin-top:16px;padding:10px 12px;border-radius:6px;background:#f5f5f5;"
    "font-size:.9rem;min-height:1.2em;color:#333}\n"
    "#clockbox{margin:0 0 20px;padding:14px 16px;border-radius:8px;background:#111;"
    "color:#5cff5c;text-align:center}\n"
    "#liveclock{font-family:'Courier New',monospace;font-size:2rem;font-weight:700;"
    "letter-spacing:2px}\n"
    "#clockmeta{font-size:.72rem;color:#8aa88a;margin-top:6px;word-break:break-all}\n"
    "#track_list{list-style:none;margin:0;padding:0}\n"
    "#track_list li{display:flex;align-items:center;justify-content:space-between;"
    "padding:12px 10px;margin-bottom:6px;border:1px solid #ddd;border-radius:8px;"
    "cursor:pointer;background:#fafafa;min-height:44px}\n"
    "#track_list li:active{background:#eee}\n"
    "#track_list li.active{border-color:#5e35b1;background:#f3e8ff}\n"
    "#track_list li.playing{border-color:#43a047;background:#e8f5e9}\n"
    "#track_list li.paused{border-color:#fb8c00;background:#fff3e0}\n"
    ".track-name{font-size:.95rem;font-weight:600}\n"
    ".track-state{font-size:.8rem;color:#666;min-width:4.5em;text-align:right}\n"
    "#track_meta{font-size:.85rem;color:#666;margin:6px 0 10px;min-height:1.2em}\n"
    ".rtc-status{display:flex;align-items:center;gap:10px;margin:8px 0 12px;padding:10px 12px;"
    "border-radius:8px;background:#f9f9f9;border:1px solid #e0e0e0}\n"
    ".rtc-led{flex:0 0 14px;width:14px;height:14px;border-radius:50%;"
    "box-shadow:0 0 6px currentColor}\n"
    ".rtc-led--yellow{background:#fbc02d;color:#fbc02d}\n"
    ".rtc-led--green{background:#43a047;color:#43a047}\n"
    ".rtc-led--red{background:#e53935;color:#e53935}\n"
    "#rtc_status_text{font-size:.88rem;color:#444;line-height:1.3}\n"
    "button.auto-time-btn{margin-top:8px;margin-bottom:4px;background:#1565c0;border-color:#0d47a1}\n"
    "button.auto-time-btn:active{background:#0d47a1}\n"
    ".period-card{margin:12px 0;padding:12px;border:1px solid #ddd;border-radius:8px;background:#fafafa}\n"
    ".period-card h3{margin:0 0 10px;font-size:1rem}\n"
    ".period-hint{font-size:.82rem;color:#666;margin:0 0 12px;line-height:1.35}\n"
    ".switch-row{display:flex;align-items:center;justify-content:space-between;margin:12px 0}\n"
    ".switch-row>span{font-size:.95rem;font-weight:600}\n"
    ".switch{position:relative;display:inline-block;width:52px;height:30px;flex:0 0 52px}\n"
    ".switch input{opacity:0;width:0;height:0;margin:0;padding:0;min-height:0}\n"
    ".switch-slider{position:absolute;cursor:pointer;inset:0;background:#ccc;border-radius:30px;"
    "transition:background .2s}\n"
    ".switch-slider::before{content:'';position:absolute;height:22px;width:22px;left:4px;bottom:4px;"
    "background:#fff;border-radius:50%;transition:transform .2s}\n"
    ".switch input:checked+.switch-slider{background:#222}\n"
    ".switch input:checked+.switch-slider::before{transform:translateX(22px)}\n"
    "#nixie_brightness{accent-color:#fb8c00}\n"
    ".profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}\n"
    ".profile-grid .save-btn{margin-top:0;font-size:1rem;padding:14px 12px}\n"
    ".profile-grid .load-btn{background:#fafafa;color:#222;border-color:#ccc;font-weight:600}\n"
    ".profile-grid .load-btn:active{background:#eee}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<h2>Nixie Clock Setup</h2>\n"
    "<section class=\"page active\" data-page=\"time\">\n"
    "<div id=\"clockbox\">\n"
    "<div id=\"liveclock\">--:--:--</div>\n"
    "<div id=\"clockmeta\">reading RTC&hellip;</div>\n"
    "</div>\n"
    "<div class=\"rtc-status\">"
    "<span id=\"rtc_led\" class=\"rtc-led rtc-led--yellow\"></span>"
    "<span id=\"rtc_status_text\">Checking RTC&hellip;</span></div>\n"
    "<button type=\"button\" class=\"save-btn auto-time-btn\" onclick=\"autoUpdateTime()\">"
    "Auto update time</button>\n"
    "<label>Alarm Enabled</label>\n"
    "<select id=\"alarm_en\"><option value=\"0\">Off</option><option value=\"1\">On</option></select>\n"
    "<label>Alarm Time</label>\n"
    "<input type=\"time\" id=\"alarm\" step=\"1\">\n"
    "<label>Alarm Track</label>\n"
    "<select id=\"alarm_track\"><option value=\"\">Loading tracks&hellip;</option></select>\n"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveAlarm()\">Save alarm</button>\n"
    "<p class=\"period-hint\">During the scheduled window the tubes and LED backlight turn off. "
    "Press any button to show the time for 5 seconds with the tubes at fixed brightness 50 "
    "(LED stays off).</p>\n"
    "<div class=\"switch-row\"><span>Hibernate mode</span>"
    "<label class=\"switch\"><input type=\"checkbox\" id=\"hib_en\">"
    "<span class=\"switch-slider\"></span></label></div>\n"
    "<label>Start</label><input type=\"time\" id=\"hib_start\" value=\"00:00\">\n"
    "<label>End</label><input type=\"time\" id=\"hib_end\" value=\"07:00\">\n"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveSchedule()\">Save hibernate schedule</button>\n"
    "</section>\n"
    "<section class=\"page\" data-page=\"backlight\">\n"
    "<p class=\"period-hint\">Use Load to recall a saved profile, "
    "or Save to store the current settings to a profile slot.</p>\n"
    "<label>Color</label>\n"
    "<input type=\"color\" id=\"color_picker\">\n"
    "<div class=\"rgb-row\"><label>R</label><input type=\"range\" id=\"r\" min=\"0\" max=\"255\">"
    "<span id=\"r_val\"></span></div>\n"
    "<div class=\"rgb-row\"><label>G</label><input type=\"range\" id=\"g\" min=\"0\" max=\"255\">"
    "<span id=\"g_val\"></span></div>\n"
    "<div class=\"rgb-row\"><label>B</label><input type=\"range\" id=\"b\" min=\"0\" max=\"255\">"
    "<span id=\"b_val\"></span></div>\n"
    "<label>Brightness <span id=\"brightness_val\"></span></label>\n"
    "<input type=\"range\" id=\"brightness\" min=\"0\" max=\"255\">\n"
    "<label>Animation</label>\n"
    "<select id=\"backlight_effect\">"
    "<option value=\"0\">Static</option>"
    "<option value=\"1\">Breath</option>"
    "<option value=\"2\">Rainbow</option>"
    "<option value=\"3\">Off</option></select>\n"
    "<label>Nixie Tube Brightness <span id=\"nixie_brightness_val\"></span></label>\n"
    "<input type=\"range\" id=\"nixie_brightness\" min=\"0\" max=\"255\">\n"
    "<div class=\"switch-row\"><span>Fade Digit Transition</span>"
    "<label class=\"switch\"><input type=\"checkbox\" id=\"nixie_transition\">"
    "<span class=\"switch-slider\"></span></label></div>\n"
    "<label>Backlight Profiles</label>\n"
    "<div class=\"profile-grid\">"
    "<button type=\"button\" class=\"save-btn load-btn\" onclick=\"loadProfile(0)\">Load 1</button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(0)\">Save 1</button>"
    "<button type=\"button\" class=\"save-btn load-btn\" onclick=\"loadProfile(1)\">Load 2</button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(1)\">Save 2</button>"
    "<button type=\"button\" class=\"save-btn load-btn\" onclick=\"loadProfile(2)\">Load 3</button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(2)\">Save 3</button>"
    "<button type=\"button\" class=\"save-btn load-btn\" onclick=\"loadProfile(3)\">Load 4</button>"
    "<button type=\"button\" class=\"save-btn\" onclick=\"saveProfile(3)\">Save 4</button>"
    "</div>\n"
    "</section>\n"
    "<section class=\"page\" data-page=\"audio\">\n"
    "<label>Volume <span id=\"volume_val\"></span></label>\n"
    "<input type=\"range\" id=\"volume\" min=\"0\" max=\"100\">\n"
    "<label>Tracks</label>\n"
    "<div id=\"track_meta\">Loading tracks&hellip;</div>\n"
    "<ul id=\"track_list\"></ul>\n"
    "</section>\n"
    "<div id=\"status\"></div>\n"
    "<nav class=\"nav\">\n"
    "<button type=\"button\" class=\"nav-btn active\" data-page=\"time\">Time</button>\n"
    "<button type=\"button\" class=\"nav-btn\" data-page=\"backlight\">Light</button>\n"
    "<button type=\"button\" class=\"nav-btn\" data-page=\"audio\">Audio</button>\n"
    "</nav>\n"
    "<script>\n"
    "let hibLiveTimer,volTimer,loading=false,rtcSyncing=false,clockBase=null,audioState={track:0,state:'stopped'},"
    "savedAlarmTrack=1,savedProfiles=[];\n"
    "function pad2(n){return String(parseInt(n,10)||0).padStart(2,'0');}\n"
    "function intVal(id,fallback){var v=parseInt(document.getElementById(id).value,10);"
    "return isNaN(v)?fallback:v;}\n"
    "function updateRtcIndicator(j,errMsg){var led=document.getElementById('rtc_led'),"
    "txt=document.getElementById('rtc_status_text');led.className='rtc-led';"
    "if(errMsg){led.classList.add('rtc-led--red');txt.textContent=errMsg;return;}"
    "if(!j){led.classList.add('rtc-led--yellow');txt.textContent='Checking RTC\\u2026';return;}"
    "if(j.rtc_calibrated&&j.time_valid&&!j.osf){led.classList.add('rtc-led--green');"
    "txt.textContent='RTC calibrated';return;}"
    "if(!j.time_valid){led.classList.add('rtc-led--red');"
    "txt.textContent='RTC error: time invalid';return;}"
    "if(j.osf){led.classList.add('rtc-led--yellow');"
    "txt.textContent='RTC needs calibration (backup power lost)';return;}"
    "led.classList.add('rtc-led--yellow');"
    "txt.textContent='RTC not calibrated \\u2013 tap Auto update time';}\n"
    "function phoneLocalNow(){var now=new Date(),tz=-now.getTimezoneOffset()/60,"
    "date=now.getFullYear()+'-'+pad2(now.getMonth()+1)+'-'+pad2(now.getDate()),"
    "time=pad2(now.getHours())+':'+pad2(now.getMinutes())+':'+pad2(now.getSeconds());"
    "return{tz:tz,date:date,time:time,timeStr:date+' '+time};}\n"
    "function timeSyncStatusMsg(j){if(j.rtc_calibrated&&j.time_valid&&!j.osf)"
    "return{ok:true,msg:'Time synced successfully'};"
    "if(j.osf)return{ok:false,msg:'Warning: RTC backup power lost (OSF set) \\u2013 re-sync time'};"
    "if(!j.time_valid)return{ok:false,msg:'RTC error: write failed or RTC unavailable'};"
    "return{ok:false,msg:'RTC error: calibration flag not set after sync'};}\n"
    "async function verifyTimeSync(){await new Promise(function(res){setTimeout(res,700);});"
    "var tr=await fetch('/api/time');if(!tr.ok)throw new Error('could not read time after sync');"
    "return tr.json();}\n"
    "function fmtLocal(utcEpoch,tz){var e=utcEpoch+tz*3600;"
    "var d=new Date(e*1000);"
    "return d.getUTCFullYear()+'-'+pad2(d.getUTCMonth()+1)+'-'+pad2(d.getUTCDate())+' '+"
    "pad2(d.getUTCHours())+':'+pad2(d.getUTCMinutes())+':'+pad2(d.getUTCSeconds());}\n"
    "function fmtTz(tz){return 'UTC'+(tz>=0?'+':'')+tz;}\n"
    "async function syncClock(){try{var r=await fetch('/api/time'),j=await r.json();"
    "if(!rtcSyncing)updateRtcIndicator(j,null);"
    "if(j.time_valid&&typeof j.unix_utc==='number'){"
    "clockBase={utc:j.unix_utc,perf:Date.now(),tz:j.tz_offset||0,osf:j.osf};"
    "tickClock();}"
    "else{clockBase=null;"
    "document.getElementById('liveclock').textContent='RTC not set';"
    "document.getElementById('clockmeta').textContent="
    "'time invalid \\u2013 tap Auto update time';}"
    "}catch(e){if(!rtcSyncing)updateRtcIndicator(null,'RTC error: could not reach device');}}\n"
    "function tickClock(){if(!clockBase)return;"
    "var nowUtc=clockBase.utc+Math.floor((Date.now()-clockBase.perf)/1000);"
    "document.getElementById('liveclock').textContent=fmtLocal(nowUtc,clockBase.tz);"
    "var meta='Local time ('+fmtTz(clockBase.tz)+')';"
    "if(clockBase.osf)meta+=' | OSF set';"
    "document.getElementById('clockmeta').textContent=meta;}\n"
    "setInterval(tickClock,1000);setInterval(syncClock,10000);syncClock();\n"
    "function normalizeAlarm(v){if(!v)return'';const p=v.split(':');"
    "return pad2(p[0]||0)+':'+pad2(p[1]||0)+':'+pad2(p[2]||0);}\n"
    "function hwToPct(v){return Math.round(v/30*100);}\n"
    "function pctToHw(v){return Math.round(v/100*30);}\n"
    "function rgbToHex(r,g,b){return'#'+[r,g,b].map(function(x){"
    "var h=parseInt(x).toString(16);return h.length===1?'0'+h:h;}).join('');}\n"
    "function hexToRgb(hex){var m=/^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(hex);"
    "return m?{r:parseInt(m[1],16),g:parseInt(m[2],16),b:parseInt(m[3],16)}"
    ":{r:0,g:0,b:0};}\n"
    "function setRgb(r,g,b){document.getElementById('r').value=r;"
    "document.getElementById('g').value=g;document.getElementById('b').value=b;"
    "document.getElementById('r_val').textContent=r;"
    "document.getElementById('g_val').textContent=g;"
    "document.getElementById('b_val').textContent=b;"
    "document.getElementById('color_picker').value=rgbToHex(r,g,b);}\n"
    "function scheduleVolume(){if(loading)return;clearTimeout(volTimer);"
    "volTimer=setTimeout(applyVolume,200);}\n"
    "async function applyVolume(){var body={volume:"
    "pctToHw(parseInt(document.getElementById('volume').value))};"
    "try{await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch(e){}}\n"
    "async function saveProfile(index){var body={save_profile_index:index,backlight_rgb:"
    "document.getElementById('r').value+','+document.getElementById('g').value+','"
    "+document.getElementById('b').value,backlight_brightness:"
    "parseInt(document.getElementById('brightness').value),"
    "backlight_effect:parseInt(document.getElementById('backlight_effect').value),"
    "nixie_brightness:parseInt(document.getElementById('nixie_brightness').value),"
    "nixie_transition:document.getElementById('nixie_transition').checked?1:0};"
    "try{var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "document.getElementById('status').textContent=r.ok?"
    "'Profile '+(index+1)+' saved':'Failed to save profile';"
    "if(r.ok){savedProfiles[index]={r:intVal('r',0),g:intVal('g',0),b:intVal('b',0),"
    "backlight_brightness:intVal('brightness',128),"
    "backlight_effect:intVal('backlight_effect',0),"
    "nixie_brightness:intVal('nixie_brightness',255),"
    "nixie_transition:document.getElementById('nixie_transition').checked?1:0};}"
    "}catch(e){document.getElementById('status').textContent='Failed to save profile';}}\n"
    "function loadProfile(index){var p=savedProfiles[index];if(!p)return;"
    "setRgb(p.r||0,p.g||0,p.b||0);"
    "document.getElementById('brightness').value=p.backlight_brightness??128;"
    "document.getElementById('brightness_val').textContent=p.backlight_brightness??128;"
    "document.getElementById('backlight_effect').value=p.backlight_effect??0;"
    "document.getElementById('nixie_brightness').value=p.nixie_brightness??255;"
    "document.getElementById('nixie_brightness_val').textContent=p.nixie_brightness??255;"
    "document.getElementById('nixie_transition').checked=(p.nixie_transition??0)==1;"
    "document.getElementById('status').textContent='Loaded profile '+(index+1);"
    "setTimeout(function(){var s=document.getElementById('status');"
    "if(s.textContent==='Loaded profile '+(index+1))s.textContent='';},2000);}\n"
    "async function autoUpdateTime(){if(rtcSyncing)return;rtcSyncing=true;"
    "document.getElementById('rtc_led').className='rtc-led rtc-led--yellow';"
    "document.getElementById('rtc_status_text').textContent="
    "'Syncing time from this device\\u2026';"
    "try{var loc=phoneLocalNow();"
    "var body={tz_offset:loc.tz,time:loc.timeStr,"
    "alarm_enabled:document.getElementById('alarm_en').value==1,"
    "alarm_time:normalizeAlarm(document.getElementById('alarm').value)};"
    "var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(!r.ok){updateRtcIndicator(null,'RTC error: server rejected time ('+r.status+')');"
    "document.getElementById('status').textContent='RTC error: save failed ('+r.status+')';"
    "rtcSyncing=false;return;}"
    "var tj=await verifyTimeSync(),st=timeSyncStatusMsg(tj);"
    "updateRtcIndicator(tj,null);"
    "document.getElementById('status').textContent=st.msg;"
    "if(st.ok)syncClock();"
    "}catch(e){updateRtcIndicator(null,'RTC error: '+e.message);"
    "document.getElementById('status').textContent='RTC error: '+e.message;}"
    "rtcSyncing=false;}\n"
    "function normalizeHm(v){if(!v)return'00:00';const p=v.split(':');"
    "return pad2(p[0]||0)+':'+pad2(p[1]||0);}\n"
    "function loadHibernation(h){if(!h)return;"
    "document.getElementById('hib_en').checked=!!h.enabled;"
    "document.getElementById('hib_start').value=normalizeHm(h.start||'00:00');"
    "document.getElementById('hib_end').value=normalizeHm(h.end||'07:00');}\n"
    "function collectHibernation(){return{"
    "enabled:document.getElementById('hib_en').checked,"
    "start:normalizeHm(document.getElementById('hib_start').value),"
    "end:normalizeHm(document.getElementById('hib_end').value)"
    "};}\n"
    "async function saveSchedule(){var ok=await applyHibLive();"
    "document.getElementById('status').textContent=ok?'Hibernate schedule saved':'Failed to save hibernate schedule';}\n"
    "function scheduleHibLive(){if(loading)return;clearTimeout(hibLiveTimer);"
    "hibLiveTimer=setTimeout(applyHibLive,200);}\n"
    "async function applyHibLive(){var body={hibernation:collectHibernation()};"
    "try{var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(!r.ok)document.getElementById('status').textContent='Failed to save hibernate schedule';"
    "return r.ok;}catch(e){document.getElementById('status').textContent='Failed to save hibernate schedule';"
    "return false;}}\n"
    "async function saveAlarm(){var at=document.getElementById('alarm_track').value;"
    "var body={alarm_enabled:document.getElementById('alarm_en').value==1,"
    "alarm_time:normalizeAlarm(document.getElementById('alarm').value)};"
    "if(at)body.alarm_track=parseInt(at,10);"
    "var r=await fetch('/api/settings',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
    "if(!r.ok){document.getElementById('status').textContent=await r.text();return;}"
    "document.getElementById('status').textContent='Alarm saved';"
    "syncClock();}\n"
    "document.getElementById('color_picker').addEventListener('change',function(){"
    "var c=hexToRgb(this.value);setRgb(c.r,c.g,c.b);});\n"
    "['r','g','b'].forEach(function(id){document.getElementById(id).addEventListener('input',"
    "function(){document.getElementById(id+'_val').textContent=this.value;"
    "document.getElementById('color_picker').value=rgbToHex("
    "document.getElementById('r').value,document.getElementById('g').value,"
    "document.getElementById('b').value);});});\n"
    "document.getElementById('brightness').addEventListener('input',function(){"
    "document.getElementById('brightness_val').textContent=this.value;});\n"
    "document.getElementById('nixie_brightness').addEventListener('input',function(){"
    "document.getElementById('nixie_brightness_val').textContent=this.value;});\n"
    "document.getElementById('volume').addEventListener('input',function(){"
    "document.getElementById('volume_val').textContent=this.value+'%';scheduleVolume();});\n"
    "document.getElementById('hib_en').addEventListener('change',scheduleHibLive);\n"
    "document.getElementById('hib_start').addEventListener('change',scheduleHibLive);\n"
    "document.getElementById('hib_end').addEventListener('change',scheduleHibLive);\n"
    "function trackStateLabel(s){return s==='playing'?'\\u25b6 Playing':"
    "s==='paused'?'\\u23f8 Paused':'\\u25cb Stopped';}\n"
    "function populateAlarmTrackSelect(tracks){var sel=document.getElementById('alarm_track');"
    "sel.innerHTML='';tracks.forEach(function(t){var opt=document.createElement('option');"
    "opt.value=t.id;opt.textContent=t.name;sel.appendChild(opt);});"
    "if(savedAlarmTrack)sel.value=String(savedAlarmTrack);}\n"
    "function renderTracks(tracks){var ul=document.getElementById('track_list');ul.innerHTML='';"
    "tracks.forEach(function(t){var li=document.createElement('li');"
    "li.dataset.track=t.id;li.innerHTML='<span class=\"track-name\">'+t.name+'</span>'"
    "+'<span class=\"track-state\"></span>';li.onclick=function(){toggleTrack(t.id);};"
    "ul.appendChild(li);});updateTrackUi();}\n"
    "function updateTrackUi(){document.querySelectorAll('#track_list li').forEach(function(li){"
    "var id=parseInt(li.dataset.track,10),st=li.querySelector('.track-state');"
    "li.classList.remove('active','playing','paused');"
    "if(id===audioState.track&&audioState.track>0){li.classList.add('active');"
    "if(audioState.state==='playing')li.classList.add('playing');"
    "if(audioState.state==='paused')li.classList.add('paused');"
    "st.textContent=trackStateLabel(audioState.state);}else{st.textContent='';}});"
    "var meta=document.getElementById('track_meta');"
    "if(audioState.track>0&&audioState.state!=='stopped'){"
    "meta.textContent='Now: '+String(audioState.track).padStart(4,'0')+'.mp3 \\u2013 '"
    "+trackStateLabel(audioState.state);}else if(meta.dataset.loaded==='1'){"
    "meta.textContent='Tap a track to play (SD:/mp3/)';}}\n"
    "async function syncAudioStatus(){try{var r=await fetch('/api/audio/status'),j=await r.json();"
    "audioState.track=j.track||0;audioState.state=j.state||'stopped';updateTrackUi();"
    "}catch(e){}}\n"
    "function trackErrorMsg(j){if(j.error==='query_failed')"
    "return'Could not query mp3/ folder on SD card.';"
    "return'Could not read SD card';}\n"
    "async function loadTracks(){var meta=document.getElementById('track_meta');"
    "meta.textContent='Loading tracks\\u2026';try{"
    "var r=await fetch('/api/audio/tracks'),j=await r.json();"
    "if(j.error||!j.tracks||j.tracks.length===0){"
    "meta.textContent=j.error?trackErrorMsg(j):'No tracks in mp3/ folder';"
    "document.getElementById('track_list').innerHTML='';"
    "document.getElementById('alarm_track').innerHTML="
    "'<option value=\"\">No tracks available</option>';meta.dataset.loaded='0';return;}"
    "meta.dataset.loaded='1';meta.textContent=j.count+' track'+(j.count===1?'':'s')+' in mp3/';"
    "populateAlarmTrackSelect(j.tracks);renderTracks(j.tracks);await syncAudioStatus();"
    "}catch(e){meta.textContent='Failed to load tracks';}}\n"
    "async function toggleTrack(id){try{"
    "var r=await fetch('/api/audio/play',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify({track:id})});"
    "if(!r.ok)return;var j=await r.json();"
    "audioState.track=j.track||0;audioState.state=j.state||'stopped';updateTrackUi();"
    "}catch(e){}}\n"
    "setInterval(syncAudioStatus,2000);\n"
    "async function load(){loading=true;"
    "var sr=await fetch('/api/settings'),sj=await sr.json();"
    "document.getElementById('alarm_en').value=sj.alarm_enabled?1:0;"
    "document.getElementById('alarm').value=sj.alarm_time;"
    "savedAlarmTrack=sj.alarm_track||1;"
    "savedProfiles=sj.profiles||[];"
    "var rgb=sj.backlight_rgb.split(',');"
    "setRgb(parseInt(rgb[0])||0,parseInt(rgb[1])||0,parseInt(rgb[2])||0,true);"
    "document.getElementById('brightness').value=sj.backlight_brightness;"
    "document.getElementById('brightness_val').textContent=sj.backlight_brightness;"
    "document.getElementById('backlight_effect').value=sj.backlight_effect;"
    "document.getElementById('nixie_brightness').value=sj.nixie_brightness??255;"
    "document.getElementById('nixie_brightness_val').textContent=sj.nixie_brightness??255;"
    "document.getElementById('nixie_transition').checked=(sj.nixie_transition??0)==1;"
    "var vp=hwToPct(sj.volume);"
    "document.getElementById('volume').value=vp;"
    "document.getElementById('volume_val').textContent=vp+'%';"
    "loadHibernation(sj.hibernation);"
    "try{var tr=await fetch('/api/time'),tj=await tr.json();"
    "updateRtcIndicator(tj,null);"
    "if(!tj.rtc_calibrated&&!rtcSyncing){await autoUpdateTime();}"
    "}catch(e){updateRtcIndicator(null,'RTC error: could not reach device');}"
    "loading=false;loadTracks();}\n"
    "function showPage(name){document.querySelectorAll('.page').forEach(function(el){"
    "el.classList.toggle('active',el.dataset.page===name);});"
    "document.querySelectorAll('.nav-btn').forEach(function(btn){"
    "btn.classList.toggle('active',btn.dataset.page===name);});"
    "location.hash=name;}\n"
    "document.querySelectorAll('.nav-btn').forEach(function(btn){"
    "btn.addEventListener('click',function(){showPage(btn.dataset.page);});});\n"
    "var initial=(location.hash||'#time').slice(1);"
    "if(['time','backlight','audio'].indexOf(initial)<0)initial='time';"
    "showPage(initial);\n"
    "window.addEventListener('hashchange',function(){"
    "var p=(location.hash||'#time').slice(1);"
    "if(['time','backlight','audio'].indexOf(p)>=0)showPage(p);});\n"
    "load();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
